# Generated by Django 4.2 on 2024-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlissBistroApp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=16)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.IntegerField(max_length=4)),
                ('message', models.TextField()),
            ],
        ),
    ]
