# Generated by Django 4.2 on 2024-11-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlissBistroApp', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
