# Generated by Django 4.2 on 2024-11-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlissBistroApp', '0010_fooditem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(max_length=50),
        ),
    ]
